import { transposeChord } from "./harmony";
import type { Chord } from "./music";

export type ProgressionCategory = "recommended" | "jazz" | "blues" | "cycle";
export type ProgressionPreset = {
  id: string;
  name: string;
  category: ProgressionCategory;
  description: string;
  difficulty: 1 | 2 | 3;
  scale: string;
  chords: Chord[];
};
// Each tuple is relative to the selected tonic. Beat lengths permit multiple chords per bar.
type Spec = [number, string, string, number?];
const c = (spec: Spec): Chord => ({
  root: spec[0],
  type: spec[1],
  degree: spec[2],
  beats: spec[3] ?? 4,
  flat: spec[2].includes("♭"),
});
const preset = (
  id: string,
  name: string,
  category: ProgressionCategory,
  description: string,
  difficulty: 1 | 2 | 3,
  specs: Spec[],
  scale = "major",
): ProgressionPreset => ({
  id,
  name,
  category,
  description,
  difficulty,
  scale,
  chords: specs.map(c),
});
const basicBlues: Spec[] = [
  [0, "7", "I7"],
  [0, "7", "I7"],
  [0, "7", "I7"],
  [0, "7", "I7"],
  [5, "7", "IV7"],
  [5, "7", "IV7"],
  [0, "7", "I7"],
  [0, "7", "I7"],
  [7, "7", "V7"],
  [5, "7", "IV7"],
  [0, "7", "I7"],
  [7, "7", "V7"],
];
export const PROGRESSIONS: ProgressionPreset[] = [
  preset(
    "pop",
    "팝 스탠더드",
    "recommended",
    "익숙한 네 코드로 시작하는 팝의 기본",
    1,
    [
      [0, "", "I"],
      [7, "", "V"],
      [9, "m", "vi"],
      [5, "", "IV"],
    ],
  ),
  preset(
    "ballad",
    "감성 발라드",
    "recommended",
    "마이너에서 시작해 부드럽게 돌아오는 흐름",
    1,
    [
      [9, "m", "vi"],
      [5, "", "IV"],
      [0, "", "I"],
      [7, "", "V"],
    ],
  ),
  preset(
    "drive",
    "센티멘털 드라이브",
    "recommended",
    "IV–V의 상승감과 vi의 여운",
    1,
    [
      [5, "", "IV"],
      [7, "", "V"],
      [9, "m", "vi"],
      [9, "m", "vi"],
    ],
  ),
  preset(
    "easy251",
    "재즈 2-5-1",
    "recommended",
    "7화음으로 익히는 재즈의 첫 종지",
    2,
    [
      [2, "m7", "ii7"],
      [7, "7", "V7"],
      [0, "maj7", "Imaj7"],
      [0, "maj7", "Imaj7"],
    ],
  ),
  preset(
    "neosoul",
    "네오소울 / R&B",
    "recommended",
    "maj9·m9·m11의 풍성한 텐션",
    3,
    [
      [5, "maj9", "IVmaj9"],
      [4, "m9", "iii9"],
      [9, "m11", "vi11"],
      [0, "maj9", "Imaj9"],
    ],
  ),
  preset(
    "classic",
    "클래식 블루스",
    "recommended",
    "12마디의 가장 익숙한 블루스 폼",
    1,
    basicBlues,
    "blues",
  ),
  preset(
    "money",
    "머니코드 변형 (1-6-4-5)",
    "recommended",
    "밝고 따뜻한 올드 팝의 순환",
    1,
    [
      [0, "", "I"],
      [9, "m", "vi"],
      [5, "", "IV"],
      [7, "", "V"],
    ],
  ),
  preset(
    "canon",
    "캐논 진행",
    "recommended",
    "8마디로 이어지는 긴 멜로디의 바탕",
    1,
    [
      [0, "", "I"],
      [7, "", "V"],
      [9, "m", "vi"],
      [4, "m", "iii"],
      [5, "", "IV"],
      [0, "", "I"],
      [2, "m", "ii"],
      [7, "", "V"],
    ],
  ),
  preset(
    "royal",
    "왕도 진행 (4-5-3-6)",
    "recommended",
    "긴장과 여운을 이어주는 네 코드",
    2,
    [
      [5, "maj7", "IVmaj7"],
      [7, "7", "V7"],
      [4, "m7", "iii7"],
      [9, "m7", "vi7"],
    ],
  ),
  preset(
    "adult",
    "ii-V-I-vi (어른스러운)",
    "recommended",
    "9화음으로 한층 부드러운 순환",
    2,
    [
      [2, "m9", "ii9"],
      [7, "13", "V13"],
      [0, "maj9", "Imaj9"],
      [9, "m7", "vi7"],
    ],
  ),
  preset(
    "twofive",
    "투-파이브 (ii-V)",
    "jazz",
    "서브도미넌트에서 도미넌트로",
    2,
    [
      [2, "m7", "ii7"],
      [7, "7", "V7"],
    ],
  ),
  preset(
    "cadence",
    "V-I 종지",
    "jazz",
    "긴장을 만들고 메이저 토닉으로 해결",
    2,
    [
      [7, "7", "V7"],
      [0, "maj7", "Imaj7"],
    ],
  ),
  preset(
    "turn-basic",
    "도돌이 (I-vi-ii-V)",
    "jazz",
    "기본적인 재즈 턴어라운드",
    2,
    [
      [0, "maj7", "Imaj7"],
      [9, "m7", "vi7"],
      [2, "m7", "ii7"],
      [7, "7", "V7"],
    ],
  ),
  preset(
    "twofiveone",
    "투-파이브-원 (ii-V-I)",
    "jazz",
    "재즈 화성의 중심이 되는 세 코드",
    2,
    [
      [2, "m7", "ii7"],
      [7, "7", "V7"],
      [0, "maj7", "Imaj7"],
    ],
  ),
  preset(
    "minor251",
    "마이너 투-파이브-원",
    "jazz",
    "반감7과 ♭9 도미넌트의 단조 해결",
    3,
    [
      [2, "m7b5", "iiø7"],
      [7, "7b9", "V7♭9"],
      [0, "m7", "i7"],
    ],
    "minor",
  ),
  preset(
    "secondary",
    "세컨더리 투-파이브",
    "jazz",
    "VI7 = V/ii, ii로 향하는 세컨더리 도미넌트",
    3,
    [
      [9, "7", "VI7 · V/ii"],
      [2, "m7", "ii7"],
      [7, "7", "V7"],
      [0, "maj7", "Imaj7"],
    ],
  ),
  preset(
    "3625",
    "3-6-2-5 (iii-VI-ii-V)",
    "jazz",
    "도미넌트 VI7로 더 강한 순환",
    2,
    [
      [4, "m7", "iii7"],
      [9, "7", "VI7"],
      [2, "m7", "ii7"],
      [7, "7", "V7"],
    ],
  ),
  preset(
    "tritone",
    "트라이톤 대리 종지",
    "jazz",
    "V7 대신 ♭II7, 반음으로 토닉에 해결",
    3,
    [
      [2, "m9", "ii9"],
      [1, "9#11", "♭II9♯11"],
      [0, "maj9", "Imaj9"],
    ],
  ),
  preset(
    "basic-blues",
    "베이직 블루스 (12마디)",
    "blues",
    "I7·IV7·V7의 기본 블루스",
    1,
    basicBlues,
    "blues",
  ),
  preset(
    "quick-blues",
    "퀵체인지 블루스 (12마디)",
    "blues",
    "두 번째 마디에서 바로 IV7로 이동",
    2,
    basicBlues.map((s, i) => (i === 1 ? [5, "7", "IV7"] : s)),
    "blues",
  ),
  preset(
    "jazz-blues",
    "재즈 블루스 (12마디)",
    "blues",
    "♯ivdim7·ii-V와 턴어라운드",
    3,
    [
      [0, "7", "I7"],
      [5, "7", "IV7"],
      [0, "7", "I7"],
      [0, "7", "I7"],
      [5, "7", "IV7"],
      [6, "dim7", "♯ivdim7"],
      [0, "7", "I7"],
      [9, "7", "VI7"],
      [2, "m7", "ii7"],
      [7, "7", "V7"],
      [0, "7", "I7", 2],
      [9, "7", "VI7", 2],
      [2, "m7", "ii7", 2],
      [7, "7", "V7", 2],
    ],
  ),
  preset(
    "bird-blues",
    "버드 블루스 (비밥)",
    "blues",
    "12마디 안에서 이어지는 반음계 ii-V 연결",
    3,
    [
      [0, "maj7", "Imaj7"],
      [11, "m7b5", "viiø7", 2],
      [4, "7b9", "III7♭9", 2],
      [9, "m7", "vi7", 2],
      [2, "7", "II7", 2],
      [7, "m7", "v7", 2],
      [0, "7", "I7", 2],
      [5, "7", "IV7"],
      [5, "m7", "iv7", 2],
      [10, "7", "♭VII7", 2],
      [4, "m7", "iii7", 2],
      [9, "7", "VI7", 2],
      [3, "m7", "♭iii7", 2],
      [8, "7", "♭VI7", 2],
      [2, "m7", "ii7"],
      [7, "7", "V7"],
      [0, "maj7", "Imaj7", 2],
      [9, "7", "VI7", 2],
      [2, "m7", "ii7", 2],
      [7, "7", "V7", 2],
    ],
  ),
  preset(
    "minor-blues",
    "마이너 블루스 (12마디)",
    "blues",
    "i7·iv7과 단조 도미넌트의 대비",
    2,
    [
      [0, "m7", "i7"],
      [0, "m7", "i7"],
      [0, "m7", "i7"],
      [0, "m7", "i7"],
      [5, "m7", "iv7"],
      [5, "m7", "iv7"],
      [0, "m7", "i7"],
      [0, "m7", "i7"],
      [8, "7", "♭VI7"],
      [7, "7b9", "V7♭9"],
      [0, "m7", "i7"],
      [7, "7b9", "V7♭9"],
    ],
    "minor",
  ),
  preset(
    "eight-blues",
    "8마디 블루스",
    "blues",
    "짧은 폼 안에서 완성되는 블루스",
    1,
    [
      [0, "7", "I7"],
      [7, "7", "V7"],
      [5, "7", "IV7"],
      [5, "7", "IV7"],
      [0, "7", "I7"],
      [7, "7", "V7"],
      [0, "7", "I7"],
      [7, "7", "V7"],
    ],
    "blues",
  ),
  preset(
    "rhythm-a",
    "리듬체인지 A (I-VI-ii-V)",
    "cycle",
    "VI7 세컨더리 도미넌트로 추진력 더하기",
    2,
    [
      [0, "maj7", "Imaj7"],
      [9, "7", "VI7"],
      [2, "m7", "ii7"],
      [7, "7", "V7"],
    ],
  ),
  preset(
    "turnaround",
    "턴어라운드 (I-vi-ii-V)",
    "cycle",
    "m7·9·13화음으로 부드럽게 반복",
    2,
    [
      [0, "maj7", "Imaj7"],
      [9, "m7", "vi7"],
      [2, "m9", "ii9"],
      [7, "13", "V13"],
    ],
  ),
  preset(
    "backdoor",
    "백도어 (iv-♭VII-I)",
    "cycle",
    "단조에서 빌려온 iv7과 ♭VII7",
    2,
    [
      [5, "m7", "iv7"],
      [10, "7", "♭VII7"],
      [0, "maj7", "Imaj7"],
    ],
  ),
];
export const realizePreset = (preset: ProgressionPreset, root: number) =>
  preset.chords.map((chord) => transposeChord(chord, root));
